eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8000

spring:
  application:
    name: api-gateway-server
  cloud:
    gateway:
      routes:
        - id: project-micro-service
          uri:
            lb://project-micro-service
          predicates:
            - Path=/api/projects/**