eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8000

spring:
  application:
    name: api-gateway-server
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-micro-service
            uri: lb://user-micro-service
            predicates:
              - Path=/api/users/**

          - id: auth-micro-service
            uri: lb://user-micro-service
            predicates:
              - Path=/api/auth/**

          - id: team-micro-service
            uri:
              lb://team-micro-service
            predicates:
              - Path=/api/teams/**

          - id: task-micro-service
            uri:
              lb://task-micro-service
            predicates:
              - Path=/api/tasks/**

          - id: project-micro-service
            uri:
              lb://project-micro-service
            predicates:
              - Path=/api/projects/**

frontend:
  url: http://localhost:4200