spring:
  application:
    name: project-micro-service
  datasource:
    url: jdbc:postgresql://localhost:5432/projects
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8003