spring:
  application:
    name: user-micro-service
  datasource:
    url: jdbc:postgresql://localhost:5432/tma
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  app:
    jwtSecret: 0QkwkrFW82i60kglj179aelSS6NLc6N1qpgSrcV00Vbd
    jwtExpirationMs: 86400000

server:
  port: 8001